### ISSUE TITLE
Odkaz zpět / zrušit v detailu poznámky

### ISSUE THREAD

**Issue by jrkgnk** [mergado/logbook#1]
@hudecsamuel co takhle doplnit vedle tlačítka uložit textový odkaz pro zrušení / odchod zpět na výpis logu, když si uživatel rozmyslí, že poznámku napsat nechce nebo ji neuložit? 

Pokud by byla textarea vyplněna mohl by vyzkoučit dialog s potvrzením o zrušení.

![log-cancel](https://cloud.githubusercontent.com/assets/17846924/13808775/06e60b0e-eb68-11e5-88b8-8bc149d823a4.png)

**Comment by hudecsamuel** [comment]
Je to tam

![screenshot from 2016-03-17 17 08 54](https://cloud.githubusercontent.com/assets/13395909/13852594/18b35462-ec63-11e5-9c09-89a0d522af4b.png)
