### ISSUE TITLE
Widget sometimes (?) renders as a normal viewport

### ISSUE THREAD

**Issue by smuuf** [mergado/logbook#10]
I came upon this strange thing today:

![image](https://cloud.githubusercontent.com/assets/6860713/15038108/401765a2-12a1-11e6-8451-74a106862505.png)

- Mergado points to the **correct** *widget* URL
- Nevertheless the app renders as a normal page, which I found out after inspecting the contents of the `IFRAME`; as seen in the picture above
- After two (?) page refreshes the widget renders as it should (`Zatiaľ tu nemáte žiadne logy.
Zapíšte prvý!`)

It's as if there is a brief *undefined* moment in app's logic which ultimately ends up with the *normal-viewport-view* instead of the *widget-view*.

*My first impression was that it may have something to do with the OAuth authentization/authentification procedure - because it occured soon after first opening Mergado after some period of time (circa 1 day) on this computer. But who knows...*

**Comment by hudecsamuel** [comment]
We had separate issue in one of Reglendo repositories. The main cause of this was conflicting sessions (and maybe something else in oAuth), but it should be solved now.
If there ever occurs an error like this it would be something i will eventualy see in logs and can fix more easily (compared to errors with session cookies).

**Comment by smuuf** [comment]
Great :)
