### ISSUE TITLE
Export CSV nefunguje ve firefoxu

### ISSUE THREAD

**Issue by jrkgnk** [mergado/logbook#2]
@hudecsamuel ve firefoxu (Mozilla Firefox 45.0) po kliknutí na ikonku CSV (napříč místy kde se zobrazuje) se nevygeneruje / nestáhne CSV soubor. V Chrome ano.

**Comment by hudecsamuel** [comment]
Napadlo ma tam dať neakú detekciu a proste to zobraziť len v chrome. Ale zatiaľ to asi dám preč aby to nemýlilo užívateľov.

**Comment by jrkgnk** [comment]
Dobře souhlasím, pokud to do ostrého nasazení nevyřešíš tak to potom prosím na produkci skryj, děkuji.

**Comment by jrkgnk** [comment]
Pokud export nemá záznam v logbooku tak bych nenabízel (nezobrazoval ikonku) stažení CSV. Co myslíš?


![screenshot-dev mergado com-2016-03-18-09-36-44](https://cloud.githubusercontent.com/assets/17846924/13872784/101baf36-eced-11e5-97f0-1ef81772aa63.png)

**Comment by jrkgnk** [comment]
Přes pravý klik lze ve Firefoxu CSV stáhnout.

**Comment by smuuf** [comment]
Stahování lze teď udělat i přes javascriptové Mergado App Message API *(nebo jak se tomu bude nadávat)*:

Nejdřív si do stránky vložit správný soubor; odteď jej bude nabízet samo Mergado:
```
<script src="http://app.mergado.com/static/js/apps/MessageApi.js"></script>
```
**Pozor**, než až budou Mergado aplikace v ostrém provozu, nebude to `app.mergado.com`, ale **vývojářský server** - ať už samotný *Logbook* bude ve vývoji nebo v ostrém provozu.

Odkazy, které se pak otevřou v malinkém popup okně, potom označovat atributem `data-download`, jehož obsahem je název atributu, ze kterého se má brát URL, na kterou popup okno bude směřovat.

```
<a title="Odkazík" data-download="href" href="./neco.csv">Stáhnout</a>
```

**Stane se toto:**

1. Po načtení stránky se projdou elementy, které mají atribut `data-download` a na jejich `click` event se naváže callback.
2. Po kliknutí na takto označené elementy se pošle příslušná message do Mergado wrapper stránky kolem onoho `IFRAME`.
3. Zde se ve skriptech v režii Mergada zachytí zpráva z IFRAME a vytvoří se ono okno s danou URL a následně se za pět sekund automaticky zavře.
4. Soubor, který bude na nějaké URL se za těch pět sekund má stihnout **začít** stahovat; *kdyby* tam někdo hodil nějakou jinou URL, kde by měla být normální stránka, tak se za pět sekund okno automaticky zavře. Motivace k tomuto bylo zabránění nějakého zneužívání tohohle popup okna k otevírání jen-tak-nějakých stránek..

**K diskuzi:**

1. Používat hodnotu atributu `data-download` jako informaci z jakého atributu vytáhnout nějakou `URL`? Pokud se to bude používat jen u odkazů, tak by tam mohlo být natvrdo `href`. Takhle jsem to chtěl udělat univerzální, aby se to dalo kdyžtak použít i u obrázků (třeba), kde se používá `src`. Nad potřebou té univerzalitty jsem ale moc nedumal; možná není potřeba. *Názory?*
2. Možná by se dala diskutovat i doba před tím, než se zavře stahovací popup okýnko.

**Comment by hudecsamuel** [comment]
A to už je tam implementované?

**Comment by smuuf** [comment]
Ano, mělo by být. Je to součást našeho `MessageApi.js`.

**Comment by hudecsamuel** [comment]
ok po povoleni popupov to funguje ako ma (aspon u mna)
