### ISSUE TITLE
Velikost textarea pro vložení poznámky

### ISSUE THREAD

**Issue by jrkgnk** [mergado/logbook#3]
1. Velikost TA lze roztáhnout tak, že tlačítka zmizí viz obrázek. 
3. V Chrome se nezobrazuje posuvník při vložení delšího textu. Ve Firefoxu ano.

![veliksot-ta](https://cloud.githubusercontent.com/assets/17846924/13873882/ae8fc8b2-ecf4-11e5-9e14-40c7e1596b56.png)

@hudecsamuel

**Comment by hudecsamuel** [comment]
Tak nakoniec som to vyriešiel, síce som tam nenechal to manuálne rozťahovanie, ale teraz sa už automaticky bude prispôsobovať textu (tak isto to bude prispôsobovať aj výšku iframu)
