### ISSUE TITLE
Add text, if widget is empty

### ISSUE THREAD

**Issue by MichalJanik** [mergado/logbook#5]
I propose to add text, if there is no log. See preview.
![mergado-00-16-36](https://cloud.githubusercontent.com/assets/608857/14012135/09cb3226-f1a4-11e5-8de9-ebcc6ff51c80.png)

**Comment by hudecsamuel** [comment]
Good point.

![screenshot from 2016-03-24 10 29 23](https://cloud.githubusercontent.com/assets/13395909/14013228/8284af9c-f1ab-11e5-82d5-cb6a1937366a.png)

 For now we don't have any way to add links that would redirect user in mergado to (specific) application page, so for now i just added this

**Comment by MichalJanik** [comment]
I suggest to add a call to action.
For example: 

> Zatím tu nemáte žádné logy.
> Napište první!

**Comment by hudecsamuel** [comment]
Like this?

![screenshot from 2016-03-24 10 53 44](https://cloud.githubusercontent.com/assets/13395909/14013777/bebab1b6-f1ae-11e5-8735-024f8a7430e0.png)

**Comment by MichalJanik** [comment]
Amazing!
:skull:

**Comment by paveldedik** [comment]
IMO the font size is too large, it seems inconsistent with Repairman:

![prehled aqt sk heureka sk mergado](https://cloud.githubusercontent.com/assets/2439357/14019085/4c51a10c-f1d1-11e5-8285-855d56711690.png)


Also the gradient on the background should be perhaps removed as we did this in widgets of the other apps (if possible, widgets should be displayed with transparent background, i.e. the choice of a background depends on Mergado and is consistent between all widgets).

**Comment by smuuf** [comment]
For widget's `IFRAME` to be transparent we would probably have to make some changes to the `IFRAME` element's attributes directly on the Mergado side, but I like the idea!

**Comment by hudecsamuel** [comment]
Dal som preč ten shadow, a zmenšil som font na tolkoto

![screenshot from 2016-03-29 13 10 38](https://cloud.githubusercontent.com/assets/13395909/14106143/b11d455a-f5af-11e5-8fe4-035336e83109.png)
