### ISSUE TITLE
Pořadí záznamů v exportovaném CSV

### ISSUE THREAD

**Issue by jrkgnk** [mergado/logbook#7]
Ahoj,

pořadí záznamů v exportovaném CSV je jiné než v Mergadu.
![screen_20160603-29-16_01](https://cloud.githubusercontent.com/assets/17846924/14099391/66df15b0-f585-11e5-9faf-95cf7168d569.png)

![screenshot-app-mergado-2016-03-29-08-08-43](https://cloud.githubusercontent.com/assets/17846924/14099443/c739b76c-f585-11e5-9ee0-db1a15441f28.png)

**Comment by hudecsamuel** [comment]
My mistake. I found out that it was ordering it by ``created_at``, instead of ``date``
Should function correctly after I'll push it to production

**Comment by hudecsamuel** [comment]
Toto by malo fungovat, takze zatvaram.
